name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.1.app

    - name: Build and test macOS target
      run: |
        xcodebuild clean build test \
          -project PracticeFeed/PracticeFeed.xcodeproj \
          -scheme "CI_macOS" \
          CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO \
          -sdk macosx \
          -destination "platform=macOS" \
          ONLY_ACTIVE_ARCH=YES

    - name: Build and test iOS target
      run: |
        xcodebuild clean build test \
          -project PracticeFeed/PracticeFeed.xcodeproj \
          -scheme "CI_iOS" \
          CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,OS=14.0,name=iPhone 15" \
          ONLY_ACTIVE_ARCH=YES

